---
title: "Fragenbogenalyseprojekt"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(labelled)
library(readr)
library(stringr)
library(tidyr)
library(purrr)
library(forcats)
```

You can add options to executable code like this

```{r}
setwd("/Users/shaniabaffour/Desktop/Master /3. Semester/Projekt")

pne <- read_excel("Rohdatensatz 16.10.xlsx")
```

```{r}
setwd("/Users/shaniabaffour/Desktop/Master /3. Semester/Projekt")
pne3 <- read_excel("Codeplan-23.10.2025.xlsx")
```

```{r}
names(pne3)
```

## Auszählung

### Hochschule

```{r}
table(pne3$`In welchem Bundesland bist du an einer Hochschule immatrikuliert?`)
```

### Abschlussziel

```{r}
table(pne3$`Welches Abschlussziel strebst du derzeit an? `)
```

### Fachsemester

```{r}
table(pne3$`In welchem Fachsemester befindest du dich derzeit? `)
```

```{r}
table(pne3$I
```

### ärztliche Diagnose

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [ADS]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [ADHS]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Autismus]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Depression ]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Angststörungen ]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Schizophrenie]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Migräne ]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Schlafstörung (Insomnie)]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Ich habe keine der oben genannten Diagnosen]`)
```

```{r}
table(pne3$`Liegt bei dir eine ärztliche Diagnose zu einer der folgenden Erkrankungen vor?  [Sonstiges]`)
```

```{r}
table(pne3$`Hast du jemals in deinem Leben PNE konsumiert? `)
```

### kognitive Leistung

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Ginkgo Biloba]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [B - Vitamine (B12, B6) ]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Folan- und Niacin Präparate ]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Schlaf- und Beruhigungsmittel (z.B. Melatonin, Passionsblume, Baldrian)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Koffeintabletten ]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Methylphenidat (Ritalin, Mediziner, Concetta, Equasym, Rubinen)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Modafinil (Vigil)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Antidepressiva (z.B. Cipralex, Cipramil, Zoloft, Cymbalta, Fluctin, Sertralin AL)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Pflanzliche Antidepressiva (Johanniskraut)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Antidementiva (Aricept, Exelon, Reminyl, Ebixa/ Axura)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Cannabis]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Amphetamine (z.B. Speed)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [MDMA (Ecstasy)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Methamphetamine (z.B. Crystal Meth, Thaipille)]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Keine der aufgelisteten Substanzen]`)
```

### Stressbewätigung

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Ginko Biloba]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [B - Vitamine (B12, B6)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Folan- und Niacin Präparate]`)
```

```{r}
table(pne3$`Nimmst du für den Zweck der Steigerung der eigenen kognitiven Leistung eine oder mehrere der unten stehenden Substanzen ein?  [Schlaf- und Beruhigungsmittel (z.B. Melatonin, Passionsblume, Baldrian)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Koffeintabletten]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Methylphenidat (Ritalin, Mediziner, Concetta, Equasym, Rubinen)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Modafinil (Vigil)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Antidepressiva (z.B. Cipralex, Cipramil, Zoloft, Cymbalta, Flutti, Sertralin AL)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Pflanzliche Antidepressiva (Johanniskraut)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Antidementiva (Aricept, Exelon, Reminyl, Ebixa/Axura)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Cannabis]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Amphetamine (z.B. Speed)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [MDMA (Ecstasy)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Methamphetamine (z.B. Crystal Meth, Thaipille)]`)
```

```{r}
table(pne3$`Nimmst du für die eigene Stressbewältigung eine oder mehrere der unten stehenden Substanzen ein?  [Keine der aufgelisteten Substanzen]`)
```

```{r}
table(pne3$`Hast du innerhalb der folgenden Zeiträume PNE konsumiert?        [Ich habe innerhalb der letzten 12 Monate PNE konsumiert.]`)
```

```{r}
table(pne3$`Hast du innerhalb der folgenden Zeiträume PNE konsumiert?        [Ich habe innerhalb der letzten 30 Tage PNE konsumiert.]`)
```

```{r}
table(pne3$`Hast du innerhalb der folgenden Zeiträume PNE konsumiert?        [Ich habe innerhalb der letzten 7 Tage PNE konsumiert.]`)
```

### Häufigkeit

```{r}
table(pne3$`Wie häufig hast du seit Beginn deines Studiums Substanzen eingenommen, um besser mit den Anforderungen des Studiums zurechtzukommen (z. B. Mittel zur Stressbewältigung oder Leistungssteigerung)? `)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Ginkgo Biloba]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [B - Vitamine (B12, B6) ]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Folan- und Niacin Präparate ]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Schlaf- und Beruhigungsmittel (z.B. Melatonin, Passionsblume, Baldrian)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Koffeintabletten ]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Methylphenidat (Ritalin, Medikinet, Concerta, Equasym, Rubifen)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Modafinil (Vigil)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Antidepressiva (z.B. Cipralex, Cipramil, Zoloft, Cymbalta, Fluctin, Sertralin AL)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Pflanzliche Antidepressiva (Johanniskraut)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Antidementiva (Aricept, Exelon, Reminyl, Ebixa/ Axura)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Cannabis]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Amphetamine (z.B. Speed)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [MDMA (Ecstasy)]`)
```

```{r}
table(pne3$`Welche der folgenden Substanzen konsumierst du in welcher Häufigkeit? [Methamphetamine (z.B. Crystal Meth, Thaipille)]`)
```

### welche situation

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Unmittelbar vor Prüfungen, Präsentationen und anderen Leistungsnachweisen]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Während der Prüfungsvorbereitung]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Für die gleichzeitige Bewältigung von Studium und Nebenjob]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Um in Gruppenarbeiten kognitiv leistungsfähig zu bleiben]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Bei Schlafmangel ]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Während des Uni-Alltags (z.B. beim Besuch von Veranstaltungen)]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Zur Vorbereitung für Abschlussarbeiten und -Projekte]`)
```

```{r}
table(pne3$`In welchen Situationen konsumierst du PNE?   [Sonstiges]`)
```

```{r}
table(pne3$`Konnte der gewünschte Effekt erzielt werden?`)
```

### fragebogen 1

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [1. Es fällt mir schwer, mich zu konzentrieren.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [2. Ich bin schnell gedanklich abwesend. ]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [3. Es fällt mir schwer zwei Dinge gleichzeitig zu tun, selbst einfache Dinge (z. B., wenn ich rede, während ich Tee koche, vergesse ich vielleicht Wasser in die Teekanne zu füllen oder ich muss das Gespräch unterbrechen). ]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [4. Es fällt mir schwer, im Kopf zu rechnen (z. B. kann ich beim Einkaufen den Rest nicht im Kopf ausrechnen).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [5. Die Worte liegen mir auf der Zunge.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [6. Ich bin mitten in einer Aktivität gedanklich abwesend.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [7. Ich finde es schwierig, Aktivitäten zu organisieren, die vom Alltag abweichen (z. B. einen Urlaub oder ein Abendessen mit mehreren Personen).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [8. Ich habe Schwierigkeiten, mich an kürzlich erhaltene Informationen zu erinnern (z. B. den Namen einer Person oder eines Ortes).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [9. Ich finde es schwierig, Informationen abzurufen, die ich früher gut wusste (z. B. Daten historischer Ereignisse oder geografische Orte).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [10. Ich habe Schwierigkeiten, mich an Erlebnisse oder Ereignisse zu erinnern, die erst wenige Tage zurückliegen (z. B. wie ich den gestrigen Nachmittag verbracht habe oder wem ich auf der Straße begegnet bin).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [11. Ich vergesse Gegenstände, die ich mitnehmen wollte, und muss deswegen umkehren (z. B. den Müllbeutel neben der Tür oder meine Lunchbox auf dem Weg zur Arbeit).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [12. Beim Lesen (z. B. von Zeitschriften oder Büchern) muss ich die letzten Zeilen erneut lesen, um wichtige Informationen wiederzufinden (z. B. den Namen einer Figur), damit ich dem Text folgen kann.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [13. Meine Bewegungen sind nicht gut koordiniert.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [14. Ich habe das Gefühl, dass meine Bewegungen verlangsamt sind bzw. träger oder langsamer als gewöhnlich.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [15. Beim Sprechen finde ich nicht die passenden Wörter zum richtigen Zeitpunkt.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [16. Beim Sprechen finde ich nicht die richtigen Wörter, daher verwende ich stattdessen Umschreibungen oder allgemeine Begriffe (z.B.: „Reich mir mal das Ding da“).]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [17. Es fällt mir schwer, mich zu orientieren und einen bestimmten Ort/ein Ziel zu finden.]`)
```

```{r}
table(pne3$`Im Folgenden findest du eine Liste von Aussagen. Bitte lese jede Aussage sorgfältig durch und klicke auf die Antwort, die am besten auf dich zutrifft. Bitte denke bei der Auswahl deiner Antwort daran, was in den letzten 12 Monaten passiert ist.  [18. Ich bringe Daten durcheinander und kann mich nicht daran erinnern, welches Datum heute ist.]`)
```

### Fragebogen 2

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [1. Ich habe mich mit Arbeit oder anderen Sachen beschäftigt, um auf andere Gedanken zu  kommen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [2. Ich habe mich darauf konzentriert, etwas an meiner Situation zu verändern. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [3. Ich habe mir eingeredet, dass das alles nicht wahr ist. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [4. Ich habe Alkohol oder andere Mittel zu mir genommen, um mich besser zu fühlen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [5. Ich habe aufmunternde Unterstützung von anderen erhalten. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [6. Ich habe es aufgegeben, mich damit zu beschäftigen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [7. Ich habe aktiv gehandelt, um die Situation zu verbessern. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [8. Ich wollte einfach nicht glauben, dass mir das passiert. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [9. Ich habe meinen Gefühlen freien Lauf gelassen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [10. Ich habe andere Menschen um Hilfe und Rat gebeten. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [11. Um das durchzustehen, habe ich mich mit Alkohol oder anderen Mitteln besänftigt. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [12. Ich habe versucht, die Dinge von einer positiveren Seite zu betrachten. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [13. Ich habe mich selbst kritisiert und mir Vorwürfe gemacht. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [14. Ich habe versucht, mir einen Plan zu überlegen, was ich tun kann. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [15. Jemand hat mich getröstet und mir Verständnis entgegengebracht. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [16. Ich habe gar nicht mehr versucht, die Situation in den Griff zu kriegen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [17. Ich habe versucht, etwas Gutes in dem zu finden, was mir passiert ist. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [18. Ich habe Witze darüber gemacht.]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [19. Ich habe etwas unternommen, um mich abzulenken.]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [20. Ich habe mich damit abgefunden, dass es passiert ist. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [21. Ich habe offen gezeigt, wie schlecht ich mich fühle. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [22. Ich habe versucht, Halt in meinem Glauben zu finden. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [23. Ich habe versucht, von anderen Menschen Rat oder Hilfe einzuholen. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [24. Ich habe gelernt, damit zu leben. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [25. Ich habe mir viele Gedanken darüber gemacht, was hier das Richtige wäre. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [26. Ich habe mir für die Dinge, die mir widerfahren sind, selbst die Schuld gegeben. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [27. Ich habe gebetet oder meditiert. ]`)
```

```{r}
table(pne3$`Beurteile bitte, inwiefern die folgenden Aussagen in den vergangenen 12 Monaten auf dein Denken und Handeln in unangenehmen oder schwierigen Situationen zutrafen. Bitte mache für jede Aussage eine Angabe.     [28. Ich habe alles mit Humor genommen.]`)
```

### Strerssoren

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Zeitdruck ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Care-Tätigkeiten / Pflege von Angehörigen ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Erschwerte Vereinbarkeit von Studium und Erwerbstätigkeit]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Soziale Konflikte (z.B. am Arbeitsplatz, Freunde und Familie, Konflikte in der Partnerschaft)]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Umzug ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Einsamkeit]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Fehlende Wertschätzung und Anerkennung ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Erlebte Ausgrenzung (z.B. Mobbing)]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Überforderung ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Andauernde Krankheiten, Funktionseinschränkungen oder Behinderungen ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Finanzielle Situation ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Ängste (z.B. Zukunfts- und Versagensängste, Prüfungs- und Leistungsdruck, Selbstzweifel)]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Konkurrenz ]`)
```

```{r}
table(pne3$`Bitte gib an, welche Stressoren derzeit auf dich zutreffen.  [Keine der genannten]`)
```

```{r}
table(pne3$`Wie stark hast du dich in den letzten 7 Tagen gestresst gefühlt? `)
```

### Wohnsituation

```{r}
table(pne3$`Bitte gib deine aktuelle Wohnsituation an. `)
```

```{r}
table(pne3$`Bitte gib deine aktuelle Wohnsituation an.  [Sonstiges]`)
```

```{r}
table(pne3$`Wie gut sind deine Wohnbedingungen für das Lernen geeignet?   [Ich habe einen ruhigen Ort zum Lernen.]`)
```

```{r}
table(pne3$`Wie gut sind deine Wohnbedingungen für das Lernen geeignet?   [Ich habe zuverlässigen Internetzugang.]`)
```

```{r}
table(pne3$`Wie gut sind deine Wohnbedingungen für das Lernen geeignet?   [Ich habe ausreichend Platz zum Lernen.]`)
```

```{r}
table(pne3$`Wie gut sind deine Wohnbedingungen für das Lernen geeignet?   [Ich fühle mich in meiner Wohnsituation in Bezug auf das Lernen wohl.]`)
```

```{r}
table(pne3$`Wie gut sind deine Wohnbedingungen für das Lernen geeignet?   [Ich habe zuhause Zugriff auf zuverlässige technische Geräte für mein Studium (z. B. Laptop, PC, Tablet). ]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Erwerbstätigkeit ]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Familiäre Unterstützung ]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [BAföG]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Stipendium]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Studienkredit ]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Ersparnisse]`)
```

```{r}
table(pne3$`Aus welchen der folgenden Quellen bestreitest du aktuell deinen Lebensunterhalt?   [Sonstiges]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Vollzeit (mehr als 35h/Woche)]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Teilzeit (mind. 15/h Woche)]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Werkstudent*in]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Minijob]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Duales Studium]`)
```

```{r}
table(pne3$`In welchem Beschäftigungsverhältnis befindest du dich derzeit?  [Praktikum (bezahlt)]`)
```

```{r}
table(pne3$`Wie alt bist du?`)
```

```{r}
table(pne3$`Welches Geschlecht wurde dir bei der Geburt zugeordnet?`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [weiblich]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [Männlich]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [trans*]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [inter*]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [nicht-binär*]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [agender/ kein Geschlecht]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [genderfluid]`)
```

```{r}
table(pne3$`Mit welchem Geschlecht identifizierst du dich aktuell? [Sonstiges]`)
```

```{r}
table(pne3$`Hast du noch Anmerkungen, Anregungen oder Kommentare, die du uns mitgeben möchtest?`)
```
